import Head from 'next/head';
import HomePage from '@/components/banner';
import AboutUsSection from '@/components/about-us';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Satisfa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
        <AboutUsSection />
      </main>
    </div>
  );
}
